### PR TITLE
Selection range 

### PR DESCRIPTION
**Pull request by HannaParsa**

### CODE REVIEW

**Review by mahdyar — APPROVED** [review]
Thank you, @HannaParsa!

**Comment by HannaParsa** [comment]
@mahdyar 
sorry I just realized that I did not translate the course completely, would you please open my request again

**Comment by HannaParsa** [comment]
@mahdyar 
I opened another pull request, I will be working on that, please close and unmerge this pull request, sorry again.

**Comment by mahdyar** [comment]
> @mahdyar I opened another pull request, I will be working on that, please close and unmerge this pull request, sorry again.

Please merge the main branch into your new branch and continue on that. I'm gonna let this be as it is.

**Pull request merged**
