### PR TITLE
Update Hello, world!

### PR DESCRIPTION
**Pull request by mahdiHash**

### CODE REVIEW

**Comment by mahdyar** [comment]
I don't have access to my laptop, would you please also translate "Hello, world!" in the title?

**Comment by mahdyar** [comment]
> > I don't have access to my laptop, would you please also translate "Hello, world!" in the title?
> 
> I think it's better to be left original, since it's a special term that is used every time you learn a new programming language.

Well, Its Persian equivalent "سلام، دنیا!" is also quite well-known. Don't you think?

**Comment by mahdiHash** [comment]
> > > I don't have access to my laptop, would you please also translate "Hello, world!" in the title?
> > 
> > 
> > I think it's better to be left original, since it's a special term that is used every time you learn a new programming language.
> 
> Well, Its Persian equivalent(1) is also quite well-known. Don't you think?
> 
> 1. "سلام، دنیا!"

I'll translate it, then.

**Comment by mahdiHash** [comment]
I guess it's ready to merge now.

**Pull request merged**
